//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib_lenguajes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RsInventario {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public RsInventario() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lib_lenguajes.RsInventario", typeof(RsInventario).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANTIDAD.
        /// </summary>
        public static string clCantidad {
            get {
                return ResourceManager.GetString("clCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODIGO BODEGA.
        /// </summary>
        public static string clCodigoBodega {
            get {
                return ResourceManager.GetString("clCodigoBodega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODIGO ESTANTE: .
        /// </summary>
        public static string clCodigoEstante {
            get {
                return ResourceManager.GetString("clCodigoEstante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODIGO PRODUCTO.
        /// </summary>
        public static string clCodigoProducto {
            get {
                return ResourceManager.GetString("clCodigoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTADO.
        /// </summary>
        public static string clEstado {
            get {
                return ResourceManager.GetString("clEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA.
        /// </summary>
        public static string clFecha {
            get {
                return ResourceManager.GetString("clFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOMBRE.
        /// </summary>
        public static string clNombre {
            get {
                return ResourceManager.GetString("clNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANTIDAD: .
        /// </summary>
        public static string lbCantidad {
            get {
                return ResourceManager.GetString("lbCantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODIGO BODEGA: .
        /// </summary>
        public static string lbCodigoBodega {
            get {
                return ResourceManager.GetString("lbCodigoBodega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODIGO ESTANTE.
        /// </summary>
        public static string lbCodigoEstante {
            get {
                return ResourceManager.GetString("lbCodigoEstante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODIGO PRODUCTO: .
        /// </summary>
        public static string lbCodigoProducto {
            get {
                return ResourceManager.GetString("lbCodigoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTADO: .
        /// </summary>
        public static string lbEstado {
            get {
                return ResourceManager.GetString("lbEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha: .
        /// </summary>
        public static string lbFecha {
            get {
                return ResourceManager.GetString("lbFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOMBRE: .
        /// </summary>
        public static string lbNombre {
            get {
                return ResourceManager.GetString("lbNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVENTARIO.
        /// </summary>
        public static string lbSingular {
            get {
                return ResourceManager.GetString("lbSingular", resourceCulture);
            }
        }
    }
}
